name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:

  check:
    name: Check runix
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install flox
      uses: flox/install-flox-action@main
      with:
        github-access-token: ${{ secrets.NIX_GIT_TOKEN }}

    # - flox develop does not support non-interactive shells at the moment
    # - flox commands have command order isssues, to be fixed here in runix
    #   and perculate to the install-flox-action
    #
    #                                                              07/26/23

    - name: check clippy
      run: nix develop .#rust-env -c cargo clippy

    - name: check format
      run: nix develop .#rust-env -c cargo fmt --check

    - name: run tests
      run: nix develop .#rust-env -c cargo test
